BBS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import home

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('blog/', include('blog.urls')),
    path('like/', include('like.urls')),
    path('comment/', include('comment.urls')),
]

blog/urls.py
from django.urls import path, re_path

from . import views


urlpatterns = [
    path('addsite/', views.add_site, name='add_site'),
    path('typeandtag/', views.type_and_tag, name='edit_type_and_tag'),
    path('type_or_tag/add', views.add_type_or_tag, name='add_type_or_tag'),
    path('type_or_tag/del', views.delete_type_or_tag, name='delete_type_or_tag'),
    path('article/delete/', views.delete_article, name='delete_article'),
    path('article/edit/<int:article_id>/', views.edit_article, name='edit_article'),
    path('<str:username>/', views.site, name='site'),
    re_path(r'^(?P<username>\w+)/(?P<condition>type|tag|date)/(?P<param>.*)/', views.site, name='site_filter'),
    path('<str:username>/article/<int:article_id>/', views.article_detail, name='article_detail'),
]

blog/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation

from read.models import ReadDetail


# Create your models here.
class Blog(models.Model):
    site_name = models.CharField(max_length=32, verbose_name='站点名称')
    site_title = models.CharField(max_length=32, verbose_name='站点标题')
    site_theme = models.CharField(max_length=64, verbose_name='站点主题', null=True, blank=True)

    def __str__(self):
        return self.site_name

    class Meta:
        verbose_name_plural = '个人站点表'


class ArticleType(models.Model):
    type_name = models.CharField(max_length=32, verbose_name='文章分类')
    blog = models.ForeignKey(to=Blog, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '文章分类表'

    def __str__(self):
        return self.type_name


class ArticleTag(models.Model):
    tag_name = models.CharField(max_length=32, verbose_name='文章标签')
    blog = models.ForeignKey(to=Blog, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '文章标签表'

    def __str__(self):
        return self.tag_name


class Article(models.Model):
    title = models.CharField(max_length=64, verbose_name='文章标题')
    desc = models.CharField(max_length=255, verbose_name='文章简介')
    content = models.TextField(verbose_name='文章内容')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    last_edit_time = models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')

    read_detail = GenericRelation(ReadDetail)
    blog = models.ForeignKey(to=Blog, on_delete=models.CASCADE, null=True)
    article_type = models.ForeignKey(to=ArticleType, on_delete=models.CASCADE, verbose_name='文章分类', null=True)
    tags = models.ManyToManyField(to=ArticleTag, through='Article2ArticleTag', through_fields=('article', 'tag'), verbose_name='文章标签')

    class Meta:
        verbose_name_plural = '文章表'

    def __str__(self):
        return self.title


class Article2ArticleTag(models.Model):
    article = models.ForeignKey(to='Article', on_delete=models.CASCADE)
    tag = models.ForeignKey(to='ArticleTag', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '文章对应标签表'

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse

from user.models import UserInfo
from . import models
from utils.utils import MyPaginator
from .blogform import SiteForm, ArticleForm
from read.utils import read_statistics_once_read


# Create your views here.


def site(request, username, **kwargs):
    user_obj = UserInfo.objects.filter(username=username).first()
    if user_obj:
        blog_obj = user_obj.blog
        if user_obj == request.user:
            if not blog_obj:
                return redirect('add_site')
        # 个人站点下所有的文章
        article_list = models.Article.objects.filter(blog=blog_obj).all().order_by('-create_time')
        # 侧边栏条件筛选
        if kwargs:
            condition = kwargs.get('condition')
            param = kwargs.get('param')
            if condition == 'type':
                article_list = article_list.filter(article_type_id=param)
            elif condition == 'tag':
                article_list = article_list.filter(tags__id=param)
            else:
                year, month = param.split('-')
                article_list = article_list.filter(create_time__year=year, create_time__month=month)
        # 分页器
        content = MyPaginator(request, article_list, 10)

        content['user_obj'] = user_obj
        content['blog_obj'] = blog_obj
        return render(request, 'site.html', content)
    else:
        return render(request, '404.html')


def article_detail(request, username, article_id):
    article_obj = get_object_or_404(models.Article, pk=article_id, blog__userinfo__username=username)
    tag_obj = models.Article2ArticleTag.objects.filter(article_id=article_id)
    previous_article = models.Article.objects.filter(pk__lt=article_id).filter().last()
    next_article = models.Article.objects.filter(pk__gt=article_id).filter().first()

    # 设置cookie记录当前用户是否阅读此文章
    read_cookies_key = read_statistics_once_read(request, article_obj)
    response = render(request, 'article_detail.html',
                      {'article_obj': article_obj, 'username': username, 'previous_article': previous_article,
                       'next_article': next_article, 'tag_obj': tag_obj})
    response.set_cookie(read_cookies_key, 'True')
    return response


def add_site(request):
    if request.method == 'POST':
        form_obj = SiteForm(request.POST)
        back_dic = {'code': 1000, 'msg': ''}
        if form_obj.is_valid():
            cleaned_data = form_obj.cleaned_data
            site_obj = models.Blog.objects.create(**cleaned_data)
            site_obj.save()
            request.user.blog = site_obj
            request.user.save()
            back_dic['url'] = f'/blog/{request.user.username}'
        else:
            back_dic['code'] = 2000
            back_dic['msg'] = form_obj.errors
        return JsonResponse(back_dic)
    else:
        form_obj = SiteForm()
    return render(request, 'addsite.html', {'form_obj': form_obj})


def type_and_tag(request):
    user_obj = request.user
    article_types = models.ArticleType.objects.filter(blog=user_obj.blog)
    article_tags = models.ArticleTag.objects.filter(blog=user_obj.blog)
    content = {'article_types': article_types, 'article_tags': article_tags}
    return render(request, 'types_tags.html', content)


def add_type_or_tag(request):
    if request.method == 'POST':
        blog_obj = request.user.blog
        article_type = request.POST.get('article_type')
        if article_type:
            models.ArticleType.objects.create(type_name=article_type, blog=blog_obj)
        article_tag = request.POST.get('article_tag')
        if article_tag:
            models.ArticleTag.objects.create(tag_name=article_tag, blog=blog_obj)
        return redirect('/blog/typeandtag/')


def delete_type_or_tag(request):
    if request.is_ajax():
        back_dic = {'code': 1000}
        del_obj = request.POST.get('delete_for')
        del_id = request.POST.get('delete_id')
        if del_obj == 'type':
            type_obj = models.ArticleType.objects.get(pk=del_id)
            if type_obj:
                type_obj.delete()
            else:
                back_dic['code'] = 2000
        elif del_obj == 'tag':
            tag_obj = models.ArticleTag.objects.get(pk=del_id)
            if tag_obj:
                tag_obj.delete()
            else:
                back_dic['code'] = 2000
        else:
            back_dic['code'] = 2001
        return JsonResponse(back_dic)


def delete_article(request):
    if request.is_ajax():
        back_dic = {'code': 1000}
        delete_id = request.POST.get('delete_id')
        article_obj = models.Article.objects.get(pk=delete_id)
        if article_obj:
            article_obj.delete()
        else:
            back_dic['code'] = 2000
        return JsonResponse(back_dic)


def edit_article(request, article_id):
    content = {}
    article_obj = models.Article.objects.get(id=article_id)
    blog_obj = request.user.blog

    content['user_types'] = models.ArticleType.objects.filter(blog=blog_obj)
    content['article_obj_type'] = article_obj.article_type
    content['user_tags'] = models.ArticleTag.objects.filter(blog=blog_obj)
    content['article_obj_tags'] = article_obj.tags.all()
    if request.method == 'POST':
        article_obj_form = ArticleForm(request.POST)
        if article_obj_form.is_valid():
            article_obj.title = article_obj_form.cleaned_data['title']
            article_obj.content = article_obj_form.cleaned_data['content']
            article_obj.article_type_id = request.POST.get('article_type')
            article_obj.tags.set(request.POST.getlist('tags'))
            article_obj.save()
            return redirect('backend')
    else:
        article_obj_form = ArticleForm(initial={'title': article_obj.title, 'content': article_obj.content})
    content['form_obj'] = article_obj_form
    return render(request, 'edit_article.html', content)

blog/templates/addsite.html
{% extends 'base.html' %}

{% block title %}
    创作中心
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                 <div class="panel panel-primary">
                    <div class="panel-heading"><h3 class="panel-title text-center">个人站点</h3></div>
                    <div class="panel-body">
                        <form id="reg_form">
                            {% csrf_token %}
                            {% for form in form_obj %}
                                <div class="form-group">
                                    <label for="{{ form.auto_id }}">{{ form.label }}</label>
                                    {{ form }}
                                    <p class="text-danger">{{ form.errors.0 }}</p>
                                </div>
                            {% endfor %}
                            <input type="button" class="btn btn-info pull-right" value="创建" id="id_commit">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% block js %}
        <script>
            $('#id_commit').click(function () {
                $.ajax({
                    url:'',
                    type:'post',
                    data:{
                        'site_name': $('#id_site_name').val(),
                        'site_title': $('#id_site_title').val(),
                        'site_theme': $('#id_site_theme').val(),
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                    },
                    success: function (args){
                    if(args.code === 1000){
                        window.location.href = args.url;
                    }else if(args.code === 2000){
                        $.each(args.msg, function (index, obj){
                            let targetId = '#id_'+index;
                            $(targetId).next().text(obj[0]).parent().addClass('has-error')
                        })
                    }else {
                        $('#id_code').next().text(args.msg).parent().addClass('has-error')
                    }
                }

                })
            })
            $('input').focus(function () {
            $(this).next().text('').parent().removeClass('has-error')
        })
        </script>    
    {% endblock %}
{% endblock %}

blog/templates/edit_article.html
{% extends 'user/backend_base.html' %}

{% block backend %}

    <h3 class="text-center">编辑文章</h3>
    <div class="panel-body">
        <form action="" method="post" novalidate>
            {% csrf_token %}
            {% for form in form_obj %}
                <div class="form-group">
                    <label for="{{ form.auto_id }}">{{ form.label }}</label>
                    {{ form }}
                    <span class="pull-right text-danger">{{ form.errors }}</span>
                </div>
            {% endfor %}
            <p class="text" style="font-weight: 700">文章分类</p>
            <div>
                {% for type in user_types %}
                    {% if type == article_obj_type %}
                        <input type="radio" value="{{ type.pk }}" name="article_type" checked>{{ type.type_name }}
                    {% else %}
                        <input type="radio" value="{{ type.pk }}" name="article_type">{{ type.type_name }}
                    {% endif %}
                {% endfor %}
                <span class="text-danger pull-right type_error"></span>
            </div>
            <hr>
            <p class="text" style="font-weight: 700">文章标签</p>
            <div>
                {% for tag in user_tags %}
                    {% if tag in article_obj_tags %}
                        <input type="checkbox" value="{{ tag.pk }}" name="tags" checked>{{ tag.tag_name }}
                    {% else %}
                        <input type="checkbox" value="{{ tag.pk }}" name="tags">{{ tag.tag_name }}
                    {% endif %}
                {% endfor %}
                <span class="text-danger pull-right tag_error"></span>
            </div>
            <hr>
            <input type="submit" class="btn btn-info pull-right" value="提交" id="article_submit">
        </form>
    </div>

{% endblock %}

{% block js %}
    {% load static %}
    <script charset="utf-8" src="{% static 'kindeditor/kindeditor-all-min.js' %}"></script>
    <script>
        KindEditor.ready(function (K) {
            window.editor = K.create('#id_content', {
                width: '100%',
                height: '600px',
                resizeType: 1,
                uploadJson: '/user/upload_img/',
                extraFileUploadParams: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                }
            });
        });
        $('#article_submit').click(function () {
            // 前端判断内容是否为空
            $('.article_error').text('');
            if(!$('input[type=radio]').is(':checked')){
                $('.type_error').text('分类还没选择哦~');
                return false;
            }else if(!$('input[type=checkbox]').is(':checked')){
                $('.tag_error').text('标签还没选择哦~');
                return false;
            }
        })
    </script>
{% endblock %}

blog/templates/right_menu.html
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">文章分类</h3>
    </div>
    <div class="panel-body">
        <ul class="list-group">
            {% for article_type in article_types %}
                <li class="list-group-item">
                    <a href="{% url 'site_filter' username 'type' article_type.0 %}">
                        {{ article_type.1 }} ({{ article_type.2 }})</a>
                </li>
            {% empty %}
                <li>暂无分类</li>
            {% endfor %}
        </ul>
    </div>
</div>
<div  style="margin-top: 30px" class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">文章标签</h3>
    </div>
    <div class="panel-body">
        <ul class="list-group">
            {% for article_tag in article_tags %}
                <li class="list-group-item">
                    <a href="{% url 'site_filter' username 'tag' article_tag.0 %}">
                        {{ article_tag.1 }} ({{ article_tag.2 }})</a>
                </li>
            {% empty %}
                <li>暂无分类</li>
            {% endfor %}
        </ul>
    </div>
</div>
<div  style="margin-top: 30px" class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">日期归档</h3>
    </div>
    <div class="panel-body">
        <ul class="list-group">
            {% for article_date in article_dates %}
                <li class="list-group-item">
                    <a href="{% url 'site_filter' username 'date' article_date.0|date:'Y-m' %}">
                        {{ article_date.0|date:'Y年m月' }} ({{ article_date.1 }})</a>
                </li>
            {% empty %}
                <li>暂无分类</li>
            {% endfor %}
        </ul>
    </div>
</div>

blog/templates/site.html
{% extends 'base.html' %}

{% block title %}
{{ user_obj.get_name }}的个人站点
{% endblock %}

{{% block usersite %}
<a class="navbar-brand" href="#">{{ blog_obj.site_title }}</a>
{% endblock %}

{% block header %}
    <link rel="stylesheet" href="/static/user/css/{{ blog_obj.site_theme }}">
{% endblock %}





{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                {% block info %}
                <ul class="media-list">
                    {% for article_obj in page_obj %}
                      <li class="media">
                      <h4 class="media-heading"><a href="{% url 'article_detail' user_obj.username article_obj.pk %}">{{ article_obj.title}}</a></h4>
                        <div class="media-left">
                          <a href="#">
                            <img class="media-object" src="/user/media/{{ article_obj.blog.userinfo.avatar }}" alt="用户头像" width="80">
                          </a>
                        </div>
                        <div class="media-body">
                            {{ article_obj.desc }}
                        </div>
                        <div class="media-bottom pull-right">
                            <span>posted @</span>
                            <span>{{ article_obj.create_time|date:'Y-m-d H:i:s' }}</span>
                            <span>{{ article_obj.blog.userinfo.get_name }}</span>
                            {% load comment_tags %}
                            <span class="glyphicon glyphicon-comment">({% get_comment_count article_obj %})</span>
                            {% load like_tags %}
                            <span class="glyphicon glyphicon-thumbs-up">({% get_up_num article_obj %})</span>
                            {% load read_tags %}
                            <span class="glyphicon glyphicon-eye-open">({% get_read_count article_obj%})</span>
                            <a href="">编辑</a>
                        </div>
                      </li>
                      <hr>
                    {% empty %}
                        <h2>还没有文章哦~~~</h2>
                    {% endfor %}
                </ul>
                {% if is_paginated %}
                    <div aria-label="Page navigation" class="text-center">
                    <ul class="pagination">
                    <li>
                        {% if page_obj.has_previous %}
                          <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">上一页</span>
                          </a>
                        {% else %}
                            <span aria-hidden="true">上一页</span>
                        {% endif %}
                    </li>
                      {% for page_num in page_range %}
                          {% if page_num == page_obj.number %}
                              <li class="active"><span>{{ page_num }}</span></li>
                          {% else %}
                              <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                          {% endif %}
                      {% endfor %}
                    <li>
                        {% if page_obj.has_next %}
                          <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">下一页</span>
                          </a>
                        {% else %}
                            <span aria-hidden="true">下一页</span>
                        {% endif %}
                    </li>
                  </ul>
                </div>
                {% endif %}
                {% endblock %}
            </div>
            {% block right %}
                <div class="col-md-3">
                    {% load blog_tags %}
                    {% right_menu user_obj.username %}
                </div>
            {% endblock %}

        </div>
    </div>

{% endblock %}

blog/templates/types_tags.html
{% extends 'user/backend_base.html' %}

{% block title %}
    创作中心
{% endblock %}

{% block backend %}

    <div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#id_types" aria-controls="home" role="tab"
                                                      data-toggle="tab">我的分类</a></li>
            <li role="presentation"><a href="#id_tags" aria-controls="profile" role="tab" data-toggle="tab">我的标签</a>
            </li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="id_types">
                {#    展示当前用户所有的分类#}
                <table class="table table-hover table-striped">
                    <thead>
                    <tr>
                        <th>分类</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for type in article_types %}
                        <tr>
                            <td><a href="{% url 'site_filter' user.username 'type' type.pk %}">{{ type.type_name }}</a>
                            </td>
                            <td>
                                <button class="btn btn-info btn-xs del" obj_id="{{ type.pk }}" del_for="type">删除</button>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="3"><p class="text-center">还没有分类哦~~~</p></td>
                        </tr>

                    {% endfor %}
                    </tbody>
                </table>
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-info pull-right" data-toggle="modal" data-target="#typeModal">
                    添加文章分类
                </button>
            </div>
            <div role="tabpanel" class="tab-pane" id="id_tags">
                {#    展示当前用户所有的标签#}
                <table class="table table-hover table-striped">
                    <thead>
                    <tr>
                        <th>标签</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for tag in article_tags %}
                        <tr>
                            <td><a href="{% url 'site_filter' user.username 'tag' tag.pk %}">{{ tag.tag_name }}</a></td>

                            <td>
                                <button class="btn btn-info btn-xs del" obj_id="{{ tag.pk }}" del_for="tag">删除</button>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="3"><p class="text-center">还没有标签哦~~~</p></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-info pull-right" data-toggle="modal" data-target="#tagModal">
                    添加文章标签
                </button>
            </div>
        </div>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="typeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">添加文章分类</h4>
                </div>
                <form action="{% url 'add_type_or_tag' %}" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        <label for="">分类名称</label>
                        <input type="text" class="form-control addtype" name="article_type">
                        <span class="text-danger pull-right addtype_error"></span>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                        <button type="submit" class="btn btn-info" id="id_addtype">确定</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="tagModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">添加文章标签</h4>
                </div>
                <form action="{% url 'add_type_or_tag' %}" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        <label for="">标签名称</label>
                        <input type="text" class="form-control addtag" name="article_tag">
                        <span class="text-danger pull-right addtag_error"></span>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                        <button type="submit" class="btn btn-info" id="id_addtag">确定</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        $('#id_addtype').click(function () {
            if ($('.addtype').val() === '') {
                $('.addtype_error').text('分类名称不能为空哦~~~')
                return false;
            }
        })
        $('#id_addtag').click(function () {
            if ($('.addtag').val() === '') {
                $('.addtag_error').text('标签名称不能为空哦~~~')
                return false;
            }
        })
        $('.del').on('click', function () {
            $('.del').on('click', function () {
                // 先将当前标签对象存储起来
                let currentBtn = $(this);
                // 二次确认弹框
                swal({
                        title: "",
                        text: "确定要删除吗?",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonClass: "btn-danger",
                        confirmButtonText: "确定",
                        cancelButtonText: "取消",
                        closeOnConfirm: false,
                        closeOnCancel: false,
                        showLoaderOnConfirm: true
                    },
                    function (isConfirm) {
                        if (isConfirm) {
                            // 朝后端发送ajax请求删除数据之后 再弹下面的提示框
                            $.ajax({
                                url: '{% url "delete_type_or_tag" %}',
                                type: 'post',
                                data: {
                                    'delete_for': currentBtn.attr('del_for'),
                                    'delete_id': currentBtn.attr('obj_id'),
                                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                                },
                                success: function (args) {
                                    // 判断响应状态码 然后做不同的处理
                                    if (args.code === 1000) {
                                        swal("", '删除成功', "success");
                                        currentBtn.parent().parent().remove()
                                    } else if(args.code === 2000) {
                                        swal('', '数据不存在', 'error')
                                    } else if(args.code === 2001){
                                        swal('', '出现了未知的错误', 'info')
                                    }
                                }
                            })
                        } else {
                            swal("", "取消成功", "error");
                        }
                     });
            })
        })
    </script>
{% endblock %}